class Autogenerated {
  List<Radios>? _radios;

  Autogenerated({List<Radios>? radios}) {
    if (radios != null) {
      this._radios = radios;
    }
  }

  List<Radios>? get radios => _radios;
  set radios(List<Radios>? radios) => _radios = radios;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['radios'] != null) {
      _radios = <Radios>[];
      json['radios'].forEach((v) {
        _radios!.add(new Radios.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._radios != null) {
      data['radios'] = this._radios!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Radios {
  int? _id;
  String? _name;
  String? _url;
  String? _recentDate;

  Radios({int? id, String? name, String? url, String? recentDate}) {
    if (id != null) {
      this._id = id;
    }
    if (name != null) {
      this._name = name;
    }
    if (url != null) {
      this._url = url;
    }
    if (recentDate != null) {
      this._recentDate = recentDate;
    }
  }

  int? get id => _id;
  set id(int? id) => _id = id;
  String? get name => _name;
  set name(String? name) => _name = name;
  String? get url => _url;
  set url(String? url) => _url = url;
  String? get recentDate => _recentDate;
  set recentDate(String? recentDate) => _recentDate = recentDate;

  Radios.fromJson(Map<String, dynamic> json) {
    _id = json['id'];
    _name = json['name'];
    _url = json['url'];
    _recentDate = json['recent_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this._id;
    data['name'] = this._name;
    data['url'] = this._url;
    data['recent_date'] = this._recentDate;
    return data;
  }
}
