import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'package:islami/api/api_services.dart';
import 'package:islami/tabs/radio/default_button.dart';
import 'package:islami/tabs/radio/radioModel.dart';
import '../../widgets/loading_Indicator.dart';
import '../../widgets/radio_widget.dart';

class radioTab extends StatefulWidget {
  @override
  State<radioTab> createState() => _radioTabState();
}

class _radioTabState extends State<radioTab> {
  PageController? controller = PageController();
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Image.asset('images/radio_image.png'),
        Padding(
          padding: EdgeInsets.symmetric(
              vertical: MediaQuery.of(context).size.height / 18),
          child: Text(
            'إذاعة القرآن الكريم',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
        ),
        SizedBox(
          height: 200,
          child: FutureBuilder<Autogenerated>(
              future: ApiServices.getRadios(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return loadingInsicator();
                } else if (snapshot.hasError) {
                  return Text('Something went wrong');
                } else {
                  // التأكد من أن البيانات تم جلبها بنجاح
                  Autogenerated? autogenerated = snapshot.data;
                  List<Radios>? _radios = autogenerated?.radios ?? [];
                  final AudioPlayer player = AudioPlayer();

                  return PageView.builder(
                    controller:controller ,
                      scrollDirection: Axis.horizontal,
                      itemCount: _radios.length,
                      itemBuilder: (context, index) {
                        return radio_widget(
                          radios: _radios[index],
                          player: player,
                          next:(){
                            player.pause();
                            controller?.nextPage(duration: Duration(milliseconds: 1), curve: Curves.linear);
                          }, previous: (){
                          player.pause();
                          controller?.previousPage(duration: Duration(milliseconds: 1), curve: Curves.linear);
                        }
                        ); // يمكنك هنا تخصيص عنصر لكل محطة راديو من قائمة `_radios`
                      });
                }
              }),
        ),
      ],
    );
  }
}
